spring.application.name=mentor-platform
# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DBMentorPlatform
spring.datasource.username=postgres
spring.datasource.password=P@ssword1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=your-256-bit-secret-key-here-make-it-long-and-random
jwt.expiration=86400000

# WebSocket
spring.websocket.max-text-message-size=65536
